spring:

  transaction:
    default-timeout: 30s

# ------
  datasource:
    hikari:
      maximumPoolSize: 36
      minimumIdle: 18
      connectionTimeout: 15000
      idleTimeout: 300000
      maxLifetime: 540000
      validationTimeout: 1000
      leak-detection-threshold: 15000

  task:
    execution:
      pool:
        core-size: 2
        max-size: 4
        queue-capacity: 200
# ------

  jpa:
    hibernate:
      ddl-auto: validate

  sql:
    init:
      mode: never

  flyway:
    enabled: true

# ------
server:
  tomcat:
    threads:
      max: 104
      min-spare: 16
    accept-count: 100
# ------

management:
  metrics:
    enable:
      tomcat: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      app: yagubogu
      env: dev-k6
  endpoints:
    web:
      exposure:
        include: prometheus, health

security:
  token:
    access-token:
      secret-key: ${ACCESS_TOKEN_SECRET_KEY}
      expires-in: 1209600      # 14일 (초)
    refresh-token:
      secret-key: ${REFRESH_TOKEN_SECRET_KEY}
      expires-in: 1209600  # 14일 (초)

oauth:
  google:
    base-uri: 'http://wiremock:8080'
    token-info-uri: '/tokeninfo'
    client-id: mock-client-id
    connect-timeout: 180s
    read-timeout: 180s

