name: YaguBogu Backend Dev K6

on:
  push:
    branches: [ "dev-k6" ]
  workflow_dispatch:

env:
  IMAGE: yagubogu/yagubogu-backend

jobs:
  cd:
    runs-on: [ self-hosted, dev-k6 ]
    env:
      IMAGE: yagubogu/yagubogu-backend
      TAG: "dev-latest"
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_DEPLOY_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEPLOY_TOKEN }}

      - name: Pull Docker image
        run: |
          echo "Docker 이미지 pull 시작"
          docker pull $IMAGE:$TAG
          echo "Docker 이미지 pull 완료"

      - name: Stop & Remove existing container (by name)
        run: |
          set -e
          NAME="yagubogu-backend"
          if [ "$(docker ps -q -f name=^/${NAME}$)" ]; then
            echo "실행중 컨테이너 중지: $NAME"
            docker stop $NAME
          fi
          if [ "$(docker ps -aq -f name=^/${NAME}$)" ]; then
            echo "기존 컨테이너 제거: $NAME"
            docker rm $NAME
          fi
          echo "포트 80 점유 프로세스 확인 및 정리"
          sudo fuser -k -n tcp 80 || true

      - name: Run docker container
        run: |
          set -e
          NAME="yagubogu-backend"
          echo "새 Docker 컨테이너 실행..."
          docker run -d \
            --name $NAME \
            --restart unless-stopped \
            --network yagubogu-net \
            -p 80:8080 \
            -e SPRING_PROFILES_ACTIVE=dev \
            -e DB_URL="${{ secrets.DB_URL }}" \
            -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
            -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            -e MONITORING_SERVER_IP="${{ secrets.MONITORING_SERVER_IP }}" \
            -e GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
            -e ACCESS_TOKEN_SECRET_KEY="${{ secrets.ACCESS_TOKEN_SECRET_KEY_DEV }}" \
            -e REFRESH_TOKEN_SECRET_KEY="${{ secrets.REFRESH_TOKEN_SECRET_KEY }}" \
            $IMAGE:$TAG
          
          echo "컨테이너 실행 완료."  

      - name: Docker image Prune
        run: |
          echo "사용하지 않는 Docker 이미지 정리 중..."
          docker image prune -af || true
          echo "이미지 정리 완료"
